// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCommune.Custom;

#nullable disable

namespace MyCommune.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230228173222_DefaultUserCreatedDate")]
    partial class DefaultUserCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyCommune.Entities.User.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("Date");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ef660f2-a45c-4db5-9af8-387e86e4fe10"),
                            CreatedDate = new DateTime(2023, 2, 28, 23, 2, 21, 931, DateTimeKind.Local).AddTicks(5381),
                            Email = "superadmin@commune.com",
                            Mobile = "7827020076",
                            ModifiedDate = new DateTime(2023, 2, 28, 23, 2, 21, 931, DateTimeKind.Local).AddTicks(5394),
                            Name = "Super Admin",
                            Password = "Commune@123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
